### PR TITLE
Add flatpak packaging

### PR DESCRIPTION
**Pull request by Ferenc-**
Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>

### CODE REVIEW

**Comment by Ferenc-** [comment]
The link to the flathub button would be updated as soon the package is available on flathub.

**Comment by wh201906** [comment]
Thank you for this PR!
I wonder does the `serialtest.pro.patch` works if I changed the `SerialTest.pro` one day and the line number doesn't match exactly. 
Plus, what should I do to these files If I make a new release?

**Comment by Ferenc-** [comment]
> I wonder does the serialtest.pro.patch works if I changed the SerialTest.pro one day and the line number doesn't match exactly.

That is indeed a problem, ideally in the next point release that should be eliminated, but unfortunately `V0.2.2` is already out without it.

> Plus, what should I do to these files If I make a new release?

That depends on a few things. If the flatpak package would be released on flathub, and go under https://github.com/flathub, let's say  https://github.com/flathub/io.github.wh201906.serialtest. Then a new PR would be automatically opened, which moves to the next release. At least that is the intention behind the `x-checker-data`.  After test, the PR can be merged or manually corrected. Manual corrections are only needed if there were new dependencies, or the build system changed etc.

**Comment by wh201906** [comment]
OK. Thanks for your answer!

**Comment by wh201906** [comment]
@Ferenc- 
Hi. This is the project file of the next release(V0.2.3). Could you please help me to check if it works?
Compared with the patch you provided, This file has some extra code to check if PREFIX is defined. You can check it in the `# Rules for deployment.` part.

<details>
<summary>content</summary>

```
QT += core gui serialport bluetooth network printsupport
android {
    QT += androidextras
}

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    adaptivestackedwidget.cpp \
    asynccrc.cpp \
    connection.cpp \
    controlitem.cpp \
    ctrltab.cpp \
    datatab.cpp \
    devicetab.cpp \
    filetab.cpp \
    filexceiver.cpp \
    legenditemdialog.cpp \
    main.cpp \
    mainwindow.cpp \
    mycustomplot.cpp \
    mysettings.cpp \
    plottab.cpp \
    serialpinout.cpp \
    settingstab.cpp \
    util.cpp

HEADERS += \
    adaptivestackedwidget.h \
    asynccrc.h \
    connection.h \
    controlitem.h \
    ctrltab.h \
    datatab.h \
    devicetab.h \
    filetab.h \
    filexceiver.h \
    legenditemdialog.h \
    mainwindow.h \
    mycustomplot.h \
    mysettings.h \
    plottab.h \
    serialpinout.h \
    settingstab.h \
    util.h

FORMS += \
    ui/settingstab.ui \
    ui/filetab.ui \
    ui/legenditemdialog.ui \
    ui/serialpinout.ui \
    ui/devicetab.ui \
    ui/datatab.ui \
    ui/ctrltab.ui \
    ui/controlitem.ui \
    ui/mainwindow.ui \
    ui/plottab.ui

TRANSLATIONS += \
    i18n/SerialTest_zh_CN.ts

RC_ICONS = icon/icon.ico

# Rules for deployment.
qnx {
    target.path = /tmp/$${TARGET}/bin
} else: unix:!android {
    # if PREFIX is specified, use PREFIX
    isEmpty(PREFIX): target.path = /opt/$${TARGET}/bin
    else: target.path = $${PREFIX}/bin
}
!isEmpty(target.path) {
    INSTALLS += target
    message(Install path: $${target.path})
}

# Remember to change version in AndroidManifest.xml
VERSION = 0.2.3
QMAKE_TARGET_PRODUCT = "SerialTest"
QMAKE_TARGET_DESCRIPTION = "SerialTest"
QMAKE_TARGET_COMPANY = "wh201906"

DISTFILES += \
    android/AndroidManifest.xml \
    android/build.gradle \
    android/gradle.properties \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew \
    android/gradlew.bat \
    android/java/priv/wh201906/serialtest/MainActivity.java \
    android/res/values/libs.xml \
    android/res/values/strings.xml \
    android/res/values-zh-rCN/strings.xml

ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android

RESOURCES += \
    i18n/language.qrc \
    qdarkstyle/dark/darkstyle.qrc \
    qdarkstyle/light/lightstyle.qrc

exists(qcustomplot.cpp) {
    # For platforms which don't have qcp library, like Android.

    # Download qcustomplot source file at https://www.qcustomplot.com/index.php/download.
    # Extract the .cpp and .h file in src/ folder,
    # then build this project.
    message(Using qcustomplot sources)

    SOURCES += qcustomplot.cpp
    HEADERS += qcustomplot.h
} else {
    # For platforms which have qcp library. This will increase compile speed.

    # If qcustomplot library is not installed,
    # put the library file(*.so/*.dll) in the building folder,
    # then build this project.
    message(Using qcustomplot library)

    # Tell the qcustomplot header that it will be used as library:
    DEFINES += QCUSTOMPLOT_USE_LIBRARY

    # Link with debug version of qcustomplot if compiling in debug mode, else with release library:
    CONFIG(debug, release|debug) {
        win32:QCPLIB = qcustomplotd2
        else: QCPLIB = qcustomplotd
    } else {
        win32:QCPLIB = qcustomplot2
        else: QCPLIB = qcustomplot
    }

    # /app/lib/ is for Flatpak
    # no need to worry if /app/lib/ exists
    LIBS += -L/app/lib/ -L./ -l$$QCPLIB
}

```

</details>

**Comment by Ferenc-** [comment]
> Hi. This is the project file of the next release(V0.2.3). Could you please help me to check if it works?

It appears to be working well with flatpak. This way the `serialtest.pro.patch` can be eliminated.

**Comment by wh201906** [comment]
OK. I will make the changes in the next release. Thanks!

**Comment by wh201906** [comment]
@Ferenc- Hi. Sorry to bother you.
Since the flatpak metadata is in the flathub, Can I delete the metadata in this repo?(`/pack/flatpak/`)

**Comment by Ferenc-** [comment]
Well `/pack/flatpak/` can be deleted, without harming the `flathub` release.

**Comment by wh201906** [comment]
> And then there can't be ambitions on building a CI loop which would check the flatpak build automatically before releases.

Sorry I don't quite understand this. You mean testing the flatpak build in CI before a new release?

**Comment by Ferenc-** [comment]
>You mean testing the flatpak build in CI before a new release?

Yes. It would be potentially much better to immediately notice when a commit breaks the flatpak build, instead of only noticing it after a version is released.

**Comment by wh201906** [comment]
But the metadata in this repo also uses a tagged commit. I think it cannot detect the failed in the CI.
https://github.com/wh201906/SerialTest/blob/717a69a7f628b3bdcd4ef2eaf25569e008fef0f1/pack/flatpak/io.github.wh201906.serialtest.yml#L37
Plus, if I want to use CI in this repo, I can get the metadata file in the Flathub(https://github.com/flathub/io.github.wh201906.serialtest) then test the build, so I think it's redundant to store the metadata file there.

**Comment by Ferenc-** [comment]
> metadata in this repo also uses a tagged commit. 

Yes, that would be changed to the local directory in that hypothetical scenario.

> Plus, if I want to use CI in this repo, I can get the metadata file in the Flathub(https://github.com/flathub/io.github.wh201906.serialtest) then test the build, so I think it's redundant to store the metadata file there

That is also a completely viable scenario, if you are OK with depending on an external organization, in this case on `flathub`.

**Comment by wh201906** [comment]
> if you are OK with depending on an external organization

I think it's acceptable. Thank you for providing these information!

**Pull request merged**
